spring:
  application:
    name: countries
  datasource:
    url: 'jdbc:postgresql://localhost:5432/countries?currentSchema=public'
    username: postgres
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-lifetime: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true
    open-in-view: false
  graphql:
    graphiql:
      enabled: true

app:
  grpc-countries-batch-size: 10
server:
  port: 8383
